# Generated by Django 4.2 on 2023-05-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckMateApp', '0002_rename_end_date_driver_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
